Repository dartsim/dart, pull requests merged in 2018-02, with the labels that each got.

#980 Cleanup doxygen
  CMakeLists.txt
  doxygen/Doxyfile.in
Labels: status: ready to merge

#981 Add style guide documentation
  CONTRIBUTING.md
Labels: status: ready to merge

#982 Add probot-stale configuration
  .github/stale.yml
Labels: status: review needed

#979 Update clang-format configurations
  .clang-format
  dart/lcpsolver/Lemke.cpp
  dart/lcpsolver/ODELCPSolver.cpp
Labels: status: review needed

#972 Add ResourceRetriever::getFilePath()
  CHANGELOG.md
  dart/common/LocalResourceRetriever.cpp
  dart/common/LocalResourceRetriever.hpp
  dart/common/ResourceRetriever.cpp
  dart/common/ResourceRetriever.hpp
  dart/utils/CompositeResourceRetriever.cpp
  dart/utils/CompositeResourceRetriever.hpp
  dart/utils/DartResourceRetriever.cpp
  dart/utils/DartResourceRetriever.hpp
  dart/utils/PackageResourceRetriever.cpp
  dart/utils/PackageResourceRetriever.hpp
  unittests/TestHelpers.hpp
  unittests/unit/test_CompositeResourceRetriever.cpp
  unittests/unit/test_DartResourceRetriever.cpp
  unittests/unit/test_LocalResourceRetriever.cpp
  unittests/unit/test_PackageResourceRetriever.cpp
Labels: status: help wanted

#973 Render texture images when available
  dart/dynamics/MeshShape.cpp
  dart/dynamics/MeshShape.hpp
  dart/gui/osg/render/MeshShapeNode.cpp
  dart/gui/osg/render/MeshShapeNode.hpp
  data/urdf/wam/meshes/images/base_gray_128x.jpg
  data/urdf/wam/meshes/images/forearm_256x.jpg
  data/urdf/wam/meshes/images/lpu_128x.jpg
  data/urdf/wam/meshes/images/shoulder_256x.jpg
  data/urdf/wam/meshes/images/upperarm_128x.jpg
  data/urdf/wam/meshes/images/wrist_yaw_128x.jpg
  examples/osgExamples/osgWamIkFast/Helpers.cpp
Labels: status: review needed

#985 Add missing texture images of Atlas robot model
  data/sdf/materials/textures/atlas_cage_and_camera_diffuse_flat.jpg
  data/sdf/materials/textures/drc_extremities_diffuse.jpg
  data/sdf/materials/textures/drc_labels_1.jpg
  data/sdf/materials/textures/drc_torso_head_diffuse.jpg
  data/sdf/materials/textures/extremities_diffuse_unplugged.jpg
  data/sdf/materials/textures/right_leg_diffuse_unplugged.jpg
  data/sdf/materials/textures/torso_diffuse_unplugged.jpg
Labels: status: revision needed

#986 Extend createShapeNode to accept more types of arguments
  CHANGELOG.md
  dart/dynamics/BodyNode.cpp
  dart/dynamics/BodyNode.hpp
  dart/dynamics/detail/BodyNode.hpp
  unittests/regression/CMakeLists.txt
  unittests/regression/test_Issue986.cpp
Labels: status: help wanted

#991 Remove Brewfile
  .travis.yml
  Brewfile
  ci/install_osx.sh
Labels: type: maintenance

#992 Delete appveyor_install.ps1
  ci/appveyor_install.ps1
Labels: type: maintenance

#983 Use newer osx image (OS X 10.13)
  .travis.yml
Labels: type: maintenance

#993 Remove tinyxml dependency
  CHANGELOG.md
  ci/install_linux.sh
  cmake/FindTINYXML.cmake
  dart/CMakeLists.txt
  dart/utils/CMakeLists.txt
  dart/utils/XmlHelpers.hpp
  dart/utils/urdf/urdf_world_parser.cpp
  data/urdf/test/testWorld.urdf
  package.xml
Labels: status: review needed, type: enhancement

#996 Add vectorized joint limit functions
  CHANGELOG.md
  dart/dynamics/GenericJoint.hpp
  dart/dynamics/Joint.hpp
  dart/dynamics/ZeroDofJoint.cpp
  dart/dynamics/ZeroDofJoint.hpp
  dart/dynamics/detail/GenericJoint.hpp
  unittests/comprehensive/test_Joints.cpp
Labels: status: review needed

#998 Add installation test to Travis
  ci/script.sh
Labels: type: maintenance

#997 Add relative Jacobian functions to MetaSkeleton
  CHANGELOG.md
  dart/dynamics/MetaSkeleton.cpp
  dart/dynamics/MetaSkeleton.hpp
  dart/dynamics/Skeleton.hpp
  unittests/comprehensive/test_Dynamics.cpp
Labels: status: review needed

#1002 Update boost dependencies on Windows
  .appveyor.yml
  cmake/DARTFindDependencies.cmake
Labels: type: maintenance

#999 Add const qualifier to Joint::getForce()
  dart/dynamics/GenericJoint.hpp
  dart/dynamics/Joint.hpp
  dart/dynamics/ZeroDofJoint.cpp
  dart/dynamics/ZeroDofJoint.hpp
  dart/dynamics/detail/GenericJoint.hpp
Labels: status: review needed

#1000 Add hasBodyNode() and hasJoint() to MetaSkeleton
  CHANGELOG.md
  dart/dynamics/MetaSkeleton.hpp
  dart/dynamics/ReferentialSkeleton.cpp
  dart/dynamics/ReferentialSkeleton.hpp
  dart/dynamics/Skeleton.cpp
  dart/dynamics/Skeleton.hpp
  unittests/comprehensive/test_Skeleton.cpp
Labels: status: review needed

#1006 Update stale not to close issues automatically
  .github/stale.yml
Labels: type: maintenance

#1003 Add TranslationalJoint2D
  CHANGELOG.md
  dart/dynamics/CMakeLists.txt
  dart/dynamics/PlanarJoint.hpp
  dart/dynamics/TranslationalJoint2D.cpp
  dart/dynamics/TranslationalJoint2D.hpp
  dart/dynamics/detail/PlanarJointAspect.cpp
  dart/dynamics/detail/TranslationalJoint2DAspect.cpp
  dart/dynamics/detail/TranslationalJoint2DAspect.hpp
  dart/utils/SkelParser.cpp
  unittests/comprehensive/test_Joints.cpp
Labels: pr: review needed, pr: revision needed

#1010 Use global namespace resolution in macro
  CHANGELOG.md
  dart/common/Console.hpp
Labels: pr: ready to merge

#1013 Fix Eigen aliasing issue
  examples/osgExamples/osgAtlasPuppet/osgAtlasPuppet.cpp
Labels: pr: review needed

#1012 Change CollisionGroup::removeShapeFramesOf() to take MetaSkeleton
  dart/collision/CollisionGroup.hpp
  dart/collision/detail/CollisionGroup.hpp
Labels: pr: review needed

#1014 Add Mutex class
  dart/common/Mutex.cpp
  dart/common/Mutex.hpp
  dart/dynamics/MetaSkeleton.cpp
  dart/dynamics/MetaSkeleton.hpp
  dart/dynamics/ReferentialSkeleton.cpp
  dart/dynamics/ReferentialSkeleton.hpp
  dart/dynamics/Skeleton.cpp
  dart/dynamics/Skeleton.hpp
  unittests/comprehensive/test_Skeleton.cpp
Labels: pr: review needed

#1018 Update vcpkg before installing packages
  .appveyor.yml
Labels: pr: ready to merge, type: maintenance

#1020 Install ode and bullet w/o options
  ci/install_osx.sh
Labels: type: maintenance

#1019 Use simpler vcpkg commands
  .appveyor.yml
Labels: type: maintenance

#1021 Replace utils with io
  docs/readthedocs/tutorials/dominoes.md
  unittests/comprehensive/test_Joints.cpp
  unittests/regression/test_Issue986.cpp
Labels: pr: ready to merge
